title: Content Annotator
description: Content Annotator is a browser extension to annotate and collect social media data.
show_downloads: true
google_analytics: UA-144220389-1
theme: jekyll-theme-dinky